### ISSUE TITLE
Database Diagrams

### ISSUE THREAD

**Issue by abrarym** [big-data-cloud-chain/college-db#3]
Create database diagrams in the appropriate format and follow the corresponding styling.

**Requirements**
- Diagrams be well made and professional.
- Diagrams are well documented and designed.

**Comment by abrarym** [comment]
Here is the database. Let me know if I should make changes

[college_database.zip](https://github.com/big-data-cloud-chain/college-db/files/2943469/college_database.zip)

**Comment by kdarakhshan** [comment]
Amin's comments: rename student_courses to member_courses and remove the instructor_course table. Remove the course_term table so the courses table has a relationship with the term table.
